import base64

# プログラムに埋め込む画像ファイルをBase64形式に変換します


# --- 設定 ---
IMAGE_FILE_PATH = "ICON_win_volume.png"  # 変換したい画像ファイル
OUTPUT_PYTHON_FILE = "image_data.py"     # 出力先のPythonファイル名
VARIABLE_NAME = "ICON_DATA"              # Pythonファイル内に保存する変数名
# ------------

try:
    # 画像ファイルをバイナリモードで読み込む
    with open(IMAGE_FILE_PATH, "rb") as image_file:
        # Base64にエンコードし、デコードして文字列に変換
        encoded_string = base64.b64encode(image_file.read()).decode('utf-8')

    # 新しいPythonファイルに書き込む
    with open(OUTPUT_PYTHON_FILE, "w") as f:
        f.write(f"# Auto-generated by encode_image.py\n")
        f.write(f"{VARIABLE_NAME} = '{encoded_string}'\n")

    print(f"成功: '{IMAGE_FILE_PATH}' は '{OUTPUT_PYTHON_FILE}' に埋め込みデータとして保存されました。")

except FileNotFoundError:
    print(f"エラー: '{IMAGE_FILE_PATH}' が見つかりません。")
except Exception as e:
    print(f"エラーが発生しました: {e}")
